<?php

echo $this->getNavbar();

echo $this->getJumbotron();

echo $this->getButtons();

echo $this->getTables();

echo $this->getThumbnails();

echo $this->getLabels();

echo $this->getBadges();

echo $this->getDropmenu();

echo $this->getNavs();

echo $this->getAlerts();

echo $this->getProgressbar();

echo $this->getList();

echo $this->getPanels();

echo $this->getWell();

echo $this->getCarousel();