<?php
$lessons = $this->getLesson();
?>
<div class="content">

    <?php if(Core_Model_Session::get('admin_status')) : ?>
        <a class="uk-button uk-button-large uk-button-success ba-success" href="<?php echo Bootstrap::getBaseUrl();?>lesson/form/create">Create Lesson</a>

        <a class="uk-button uk-button-large uk-button-primary ba-primary" href="http//apprentice.dev/tag/form/create">&nbsp;&nbsp;Create Tags&nbsp;&nbsp;</a>
    <?php endif; ?>

    <table class="uk-table uk-table-hover">
        <h1>Lessons</h1>
        <tbody>
        <?php
        if(isset($lessons)) {
            foreach($lessons as $lesson) {

                echo '<tr>';
                echo '<td>' . $lesson->getName() . '</td>';
                echo '<td><a class="uk-button uk-button-small" href="'. Bootstrap::getBaseUrl() . 'lesson/view/id/'. $lesson->getId().'">&nbsp;&nbsp;&nbsp;&nbsp;View&nbsp;&nbsp;&nbsp;&nbsp;</a></td>';
                if(Core_Model_Session::get('admin_status')) {

                    echo '<td><a class="uk-button uk-button-small uk-button-primary" href="' . Bootstrap::getBaseUrl() . 'lesson/form/event/'. $lesson->getId() .'">Schedule</a></td>';


                    echo '<td><a class="uk-button uk-button-small uk-button-success" href="' . Bootstrap::getBaseUrl() . 'lesson/form/edit/' . $lesson->getId() .'">&nbsp;&nbsp;&nbsp;&nbsp;Edit&nbsp;&nbsp;&nbsp;&nbsp;</a></td>';

                    echo '<td><a class="uk-button uk-button-small uk-button-danger" href="' .  Bootstrap::getBaseUrl() . 'lesson/delete/id/' . $lesson->getId() .'">&nbsp;&nbsp;Delete&nbsp;&nbsp;</a></td>';
                }
            }

            echo '</tr>';
        }
        ?>
        </tbody>
    </table>
</div>
