<?php
    $lesson = $this->getLesson();
    $tags = $lesson->getTags();
    $suggestedStudents = $lesson->getData('studentInviteList');
?>
<div class="content">
    <div id="form-main">
        <div id="form-div">
            <h3>Schedule a Lesson</h3>
            <form class="uk-form" id="form" action="<?php echo Bootstrap::getBaseUrl();?>schedule/event/fire" method="post">
                <div class="uk-form-row">
                    <label>Lesson Name:</label>
                    <br>
                    <input readonly type="text" name="lesson_name" value="<?php echo $lesson->getName(); ?>">
                    <a class="uk-button uk-button-small uk-button-danger" href="<?php echo Bootstrap::getBaseUrl();?>lesson/view/index">Change</a>
                </div>
                <div class="uk-form-row">
                    <label>Description:</label>
                    <textarea type="text" name="description"><?php echo $lesson->getDescription(); ?></textarea>
                </div>
                <div class="uk-form-row">
                    <label>Tags:</label>
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myTags">
                        <?php
                        if(isset($tags)) {
                            foreach($tags as $tag) {
                                echo '<li>' . $tag . '</li>';
                            }
                        }
                        ?>
                    </ul>
                </div>
                <div class="uk-form-row">
                    <div class="uk-grid">
                        <div class="uk-width-1-2">
                            Date:
                            <input type="text" name="date" data-uk-datepicker="{format:'MM/DD/YYYY'}">
                        </div>
                        <div class="uk-width-1-2">
                            Time:
                            <div class="uk-autocomplete">
                                <input type="text" name="start_time" data-uk-timepicker="{format:'12h'}">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="uk-form-row">
                <label>Teacher:</label>
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myTeachers"></ul>
                </div>
                <div class="uk-form-row">
                    <label>Students:</label>
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myStudents">
                        <?php
                        if(isset($suggestedStudents))
                        {
                            foreach($suggestedStudents as $student) {
                                echo "<li>" . $student->getName() . "</li>";
                            }
                        }
                        ?>
                    </ul>
                </div>
                <div class="uk-form-row">
                    <div class="submit">
                        <input type="submit" value="Submit" id="button-blue"/>
                        <div class="ease"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

