<!DOCTYPE html>
<html>
<head>
    <link href="/assets/Css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/assets/Css/bootstrap-theme.min.css" rel="stylesheet"/>
    <link href="/assets/Css/styles.css" rel="stylesheet"/>
    <?php if ($this->getTitle()): ?>
        <title>C$50 Finance: <?= htmlspecialchars($this->getTitle()) ?></title>
    <?php else: ?>
        <title>C$50 Finance</title>
    <?php endif ?>
</head>
<body>
<div class="container">
    <div id="top">
        C$50 Finance
    </div>
    <div id="middle">