<body>
    <div class="container"
        <div class="span10 offset1">
            <div class="row">
                <h3>Create a Post</h3>
            </div>
            <form class="form-horizontal" action="../crud/create" method="post">
                <div class="control-group <?php !empty($authorError)? 'error':'';?>"
                    <label class="control-label">Author</label>
                    <div class="controls">
                        <input name="author" type="text" value="<?php echo !empty($author)? $author: '';?>">
                        <?php if (!empty($authorError)): ?>
                            <span class="help-inline"><?php echo $authorError;?></span>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="control-group <?php !empty($bodyError)? 'error':'';?>"
                    <label class="control-label">Body</label>
                    <div class="controls" >
                        <input name="body" type="text" value="<?php echo !empty($body)?$body:'';?>">
                        <?php if (!empty($bodyError)): ?>
                            <span class="help-inline"><?php echo $bodyError;?></span>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">Create</button>
                    <a class="btn" href="../post/index">Back</a>
                </div>
            </form>
    </div>
</body>