<body>
    <div class ="container">
        <div class="span10 offset1">
            <div class="row">
                <h3>DELETE A CUSTOMER</h3>
            </div>
            <form class="form-horizontal" action="" method="post">
                <input type="hidden" name="confirmation" value="true"/>
                <p class="alert alert-error">Are you sure you want to delete this post?</p>
                <div class ="form-actions">
                    <button type="submit" class="btn btn-danger">Yes</button>
                    <a class="btn" href="../post/index">No</a>
                </div>
            </form>
        </div>
    </div>
</body>