<body>
    <div class="container">
        <div class="row">
            <h3>PHP CRUD GRID</h3>
        </div>
        <div class="row">
            <p>
                <a href="create" class="btn btn-success">Create</a>
            </p>
            <table class="table table-striped table-boredered">
                <thead>
                <tr>
                    <th>Author</th>
                    <th>Body</th>
                </tr>
                </thead>
                <tbody>
                    <?php
                    $pdo = Core_Model_Database_Connection::getInstance();
                    $sql = 'SELECT * FROM posts';
                    foreach ($pdo->query($sql) as $row) {
                        echo '<tr>';
                        echo '<td>' . $row['author'] . '</td>';
                        echo '<td>' . $row['body'] . '</td>';
                        echo '<td width="250">';
                        echo '<a class="btn btn-default" href="../crud/read/' . $row['id'] . '">Read</a>';
                        echo '<a class="btn btn-success" href="../crud/update/' . $row['id'] . '">Update</a>';
                        echo '<a class="btn btn-danger" href="../crud/delete/' . $row['id'] . '">Delete</a>';
                        echo '</td>';
                        echo'</tr>';
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</body>