<body>
    <div class="container">
        <div class="span10 offset1">
            <div class="row">
                <h3>READ AUTHOR POST</h3>
            </div>
            <div class="form-horizontal">
                <div class="control-group">
                    <label class="control-label">Author</label>
                    <div class="controls">
                        <?php echo $this->getAuthor();?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Body</label>
                    <div class="controls">
                        <?php echo $this->getBody();?>
                    </div>
                </div>
                <div class="form-actions">
                    <a class="btn" href="../../post/index">Back</a>
                </div>
            </div>
        </div>
    </div>
</body>