<div class="content">
    <div id="form-main">
        <div id="form-div">
            <form class="uk-form" id="form" action="<?php echo Bootstrap::getBaseUrl();?>create/tag" method="post">
            <h2>Tag Creator</h2>
                <p></p>
                <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myTags"></ul>

                <div class="submit">
                    <input type="submit" value="Create" id="button-blue"/>
                    <div class="ease"></div>
                </div>
            </form>
        </div>
    </div>
</div>