<?php
    $user = $this->getData('userData');
    $lessonData = $user->getLessons();
    $hiatusToDateArray = $user->getData('hiatusToDate');
    $tags = $user->getTags();
?>

<div class="content">
    <h2>
        Name : <?php echo $user->getName(); ?>
	</h2>

	Email:
	<?php echo $user->getEmail(); ?>
    <br>
	Group:
    <?php echo $user->getGroups(); ?>
    <?php if(Core_Model_Session::get('admin_status')) : ;?>
    <br>
    Tags:
    <hr>
    <form action="<?php echo Bootstrap::getBaseUrl(); ?>user/edit/tag/<?php echo $user->getId();?>" method="post">
         <div>
            <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myTags">
                <?php
                if(isset($tags)) {
                    foreach($tags as $tag) {
                        echo '<li>' . $tag . '</li>';
                    }
                }
                ?>
            </ul>
         </div>
        <input class="uk-button uk-button-small uk-button-primary" type="submit" value="Change Tags"/>
    </form>
    <?php endif; ?>
    <hr>
	Incubation Progress:
    <div class="uk-progress">
       <?php echo '<div class="uk-progress"><div class="uk-progress-bar" style="width:' . $user->getProgress() .'%">' . $user->getProgress() . '%</div></div>'; ?>
    </div>

    <hr>
    Incubation Time:
    <div data-countdown=" <?php echo $user->getIncubation(); ?> "></div>
    <hr>
    <table class="uk-table uk-table-hover">
        <h1>Lesson Status</h1>
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Completetion status
        </th>
    </tr>
    </thead>
    <tbody>
    <?php
        if($lessonData) {
            foreach($lessonData as $lesson) {

                echo '<td>' . $lesson->getName() . '</td>';
                if(in_array($lesson->getId(), $user->getCompleted())) {
                    echo '<td>';
                    echo '<div class="uk-badge uk-badge-success">Completed</div>';
                    echo '</td>';
					if(Core_Model_Session::get('admin_status')) {
                	    echo '<td><a class="uk-button uk-button-small uk-button-primary" href="'. Bootstrap::getBaseUrl() . 'user/edit/unmark/' . $user->getId() .'/' .$lesson->getId() .'">Change</a></td>';
					}
				}
                elseif(in_array($lesson->getId(), $user->getHiatus())) {
                    echo '<td>';
                    echo '<div class="uk-badge uk-badge-warning">&nbsp;&nbsp;Expected: ' . $hiatusToDateArray[$lesson->getId()] . '&nbsp;&nbsp;</div>';
                    echo '</td>';
                    if(Core_Model_Session::get('admin_status')) {
                        echo '<td><a class="uk-button uk-button-small uk-button-primary" href="'. Bootstrap::getBaseUrl() . 'user/edit/unmark/' . $user->getId() .'/' .$lesson->getId() .'">Change</a></td>';
                    }
                }
                else {
                    echo '<td>';
                    echo '<div class="uk-badge uk-badge-danger">Incomplete</div>';
                    echo '</td>';
                    if(Core_Model_Session::get('admin_status')) {
						echo '<td><a class="uk-button uk-button-small uk-button-primary" href="' . Bootstrap::getBaseUrl() . 'user/edit/mark/' . $user->getId() .'/' .$lesson->getId() .'">Change</a></td>';
					}
                }
                echo '</tr>';
            }
        }
    ?>
    </tbody>
    </table>
	<hr>
    <?php if (Core_Model_Session::get('admin_status')) : ?>
        <a class="uk-button uk-button-small uk-button-success" href="<?php echo Bootstrap::getBaseUrl();?>user/edit/admin/<?php echo $user->getId(); ?>">Admin</a>
        <a class="uk-button uk-button-small uk-button-danger" href="<?php echo Bootstrap::getBaseUrl();?>user/delete/id/<?php echo $user->getId(); ?>">Remove</a>
    <?php endif;?>

</div>
