<div id="header">
    <div class="logo"><a href="http://apprentice.dev/"><img src="http://apprentice.dev/assets/images/ba-logo.svg" alt=""/></a></div>
    <div class="logout"><a href="http://apprentice.dev/incubate/logout/index">Logout <i class="fa fa-sign-out fa-1x"></i> </a></div>
</div>
<a class="mobile" href="#">MENU</a>
<div id="container">
    <div class="sidebar">
        <ul id="nav">
            <li><a href="http://apprentice.dev/incubate/lesson/index">Lessons</a></li>
			<li><a href="http://apprentice.dev/incubate/schedule/index">Schedule</a></li>
            <?php if(Core_Model_Session::get('admin_status')) : ?>
                <li><a href="http://apprentice.dev/incubate/user/index">Students</a></li>
                <li><a href="http://apprentice.dev/incubate/tag/index">Tags</a></li>
            <?php else :?>
                 <li><a href="http://apprentice.dev/incubate/user/profile/<?php echo Core_Model_Session::get('user_id');?>">Profile</a></li>
            <?php endif; ?>
        </ul>
    </div>
