<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2>
                    Welcome to the Incubator,
                </h2>
                <p>
                    Incubate requires your Google Plus account linked to your Blue Acorn email address
                </p>
                <p>
                    <a class="btn btn-primary btn-large" href="<?php echo $this->getAuthurl(); ?>">Sign in with Google+</a>
                </p>
            </div>
        </div>
    </div>
</div>