<div class="uk-container-center">
        <h2>
            Welcome to the Incubator,
        </h2>
        <p>
            Incubate requires your Google Plus account linked to your Blue Acorn email address
        </p>
        <p>
            <?php if($this->getAuthurl()) : ?>
                <a href="<?php echo $this->getAuthurl(); ?>">Sign in with Google+</a>
            <?php else: ?>
                You are signed in. <a href="http://apprentice.dev/incubate/logout/index">Sign out</a>
            <?php endif; ?>

        </p>
</div>