<div class="uk-container-center">
    <div>
        <h2>Create a new lesson</h2>
    </div>
    <form action="../create/lesson" class="uk-form uk-form-stacked" method="post">
        <div class="uk-form-row">
            <label class="uk-form-label" for="form-h-it">Lesson name</label>
            <div class="uk-form-controls">
                <input id="name" name="name" type="text">
            </div>
        </div>
        <div class="uk-form-row">
            <label class="uk-form-label" for="description">Description</label>
            <div class="uk-form-controls">
                <textarea id="description" name="description" cols="30" rows="5"></textarea>
            </div>
        </div>

        <div class="uk-form-row">
            <button class="uk-button uk-button-success" type="submit">Submit</button>
        </div>
    </form>
</div>