<?php
    $userData = $this->getData('userData');
    $percentageCoursesTaken = $this->getData('percentage_taken');
    $incubationTimer = date('Y-m-d', strtotime($userData->joined . "+90 days"));
    $lessonData = $this->getData('lesson_data');
    $completedCourses = $this->getData('completed_courses');

	$userId = isset($userData->user_id) ? $userData->user_id : '';
	$userName = isset($userData->name) ? $userData->name : '';
	$userEmail = isset($userData->email) ? $userData->email : '';

?>

<div class="content">
    <h2>
		User Name : <?php echo $userName; ?>
		<?php if (Core_Model_Session::get('admin_status')) : ?>
		<a class="uk-button uk-align-right uk-button-large uk-button-danger" href="http://apprentice.dev/incubate/user/admin/<?php echo $userId; ?>">Admin</a>
		<a class="uk-button uk-align-right uk-button-large uk-button-danger" href="http://apprentice.dev/incubate/user/remove/<?php echo $userId; ?>">Remove</a>
		<?php endif;?>
	</h2>

	Email:
	<?php echo $userEmail; ?>
	<hr>
	Incubation Progress:
    <div class="uk-progress">
       <?php echo '<div class="uk-progress"><div class="uk-progress-bar" style="width:' . $percentageCoursesTaken .'%">' . $percentageCoursesTaken . '%</div></div>'; ?>
    </div>
    <hr>
    Incubation Time:
    <div data-countdown=" <?php echo $incubationTimer ?> "></div>
    <hr>
    <table class="uk-table uk-table-hover uk-table-striped">
        <h1>Lesson Status</h1>
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Completetion status
        </th>
		<?php if(Core_Model_Session::get('admin_status')) : ?>
        <th>
            Change status
        </th>
		<?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php
        if($lessonData) {

            foreach($lessonData as $lesson) {

                echo '<td>' . $lesson->name . '</td>';

                if(in_array($lesson->lesson_id, $completedCourses)) {
                    echo '<td>';
                    echo '<div class="uk-badge uk-badge-success">Completed</div>';
                    echo '</td>';
					if(Core_Model_Session::get('admin_status')) {
                	    echo '<td><a class="uk-button uk-button-primary" href="http://apprentice.dev/incubate/user/delete/' . $userId .'/' .$lesson->lesson_id .'">Change</a></td>';
					}
				}
                else {
                    echo '<td>';
                    echo '<div class="uk-badge uk-badge-danger">Incomplete</div>';
                    echo '</td>';
                    if(Core_Model_Session::get('admin_status')) {
						echo '<td><a class="uk-button uk-button-primary" href="http://apprentice.dev/incubate/user/add/' . $userId .'/' .$lesson->lesson_id .'">Change</a></td>';
					}
                }

                echo '</tr>';
            }
        }

    ?>
    </tbody>
    </table>
	<hr>

</div>
