<?php
    $user = $this->getData('userData');
    $lessonData = $this->getData('lessonData');
?>

<div class="content">
    <h2>
		User Name : <?php echo $user->getName(); ?>
	</h2>

	Email:
	<?php echo $user->getEmail(); ?>
	<hr>
	Incubation Progress:
    <div class="uk-progress">
       <?php echo '<div class="uk-progress"><div class="uk-progress-bar" style="width:' . $user->getProgress() .'%">' . $user->getProgress() . '%</div></div>'; ?>
    </div>
    <hr>
    Incubation Time:
    <div data-countdown=" <?php echo $user->getIncubation(); ?> "></div>
    <hr>
    <table class="uk-table uk-table-hover uk-table-striped">
        <h1>Lesson Status</h1>
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Completetion status
        </th>
		<?php if(Core_Model_Session::get('admin_status')) : ?>
        <th>
            Change status
        </th>
		<?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php
        if($lessonData) {
            foreach($lessonData as $lesson) {

                echo '<td>' . $lesson->getName() . '</td>';

                if(in_array($lesson->getId(), $user->getCompleted())) {
                    echo '<td>';
                    echo '<div class="uk-badge uk-badge-success">Completed</div>';
                    echo '</td>';
					if(Core_Model_Session::get('admin_status')) {
                	    echo '<td><a class="uk-button uk-button-small uk-button-primary" href="http://apprentice.dev/incubate/user/delete/' . $user->getId() .'/' .$lesson->getId() .'">Change</a></td>';
					}
				}
                else {
                    echo '<td>';
                    echo '<div class="uk-badge uk-badge-danger">Incomplete</div>';
                    echo '</td>';
                    if(Core_Model_Session::get('admin_status')) {
						echo '<td><a class="uk-button uk-button-small uk-button-primary" href="http://apprentice.dev/incubate/user/add/' . $user->getId() .'/' .$lesson->getId() .'">Change</a></td>';
					}
                }

                echo '</tr>';
            }
        }

    ?>
    </tbody>
    </table>
	<hr>
    <?php if (Core_Model_Session::get('admin_status')) : ?>
        <a class="uk-button uk-button-small uk-button-success" href="http://apprentice.dev/incubate/user/admin/<?php echo $user->getId(); ?>">Admin</a>
        <a class="uk-button uk-button-small uk-button-danger" href="http://apprentice.dev/incubate/user/remove/<?php echo $user->getId(); ?>">Remove</a>
    <?php endif;?>

</div>
