
<div class="uk-container-center">
    <div>
        <h2>padawan</h2>
    </div>
    <form action="../create/user" class="uk-form uk-form-stacked" method="post">
        <div class="uk-form-row">
            <label class="uk-form-label" for="name">Student name</label>
            <div class="uk-form-controls">
                <input id="name" name="name" type="text">
            </div>
        </div>
        <div class="uk-form-row">
            <label class="uk-form-label" for="email">Email</label>
            <div class="uk-form-controls">
                <input id="email" name="email" type="text">
            </div>
        </div>


        <div class="uk-form-row">
            <span class="uk-form-label">Group</span>
            <div class="uk-form-controls uk-form-controls-text">
                <input id="AE" name="groups" value="AE" type="radio"> <label for="AE">Application Engineer</label><br>
                <input id="QA" name="groups" value="QA" type="radio"> <label for="QA">Quality Assurance</label><br>
                <input id="FE" name="groups" value="FE" type="radio"> <label for="FE">Front End</label><br>

            </div>
        </div>

        <div class="uk-form-row">
            <button class="uk-button uk-button-success" type="submit">Submit</button>
        </div>
    </form>
</div>