<?php
 	$userName = $this->getName();
	$userEmail = $this->getEmail();
?>
<div class="content">
    <div id="form-main">
        <div id="form-div">
            <form class="uk-form" id="form" action="http://apprentice.dev/incubate/register/new" method="post">

                <h2>Slow your role</h2>
                <h3>We need your role</h3>
				<p>If this information looks right, verify your job role.</p>
				<div class="uk-form-row">
					<label>Name:</label>
					<br>
					<input type="text" name="name" value="<?php if(isset($userName)){echo $userName;}?>">
				</div>
				<div class="uk-form-row">
					<label>Email:</label>
					<br>
					<input readonly type="text" name="email" value="<?php if(isset($userEmail)){echo $userEmail;}?>">
				</div>
				<div class="uk-form-row">


                    <fieldset tabindex="1" class='radioGroup'>
                        <legend>Choose wisely..</legend>
                        <input id='g1o4' name="group" value="Application Engineer" type="radio">
                        <label for='g1o4'>Application Engineer</label>
                        <input id='g1o5' name="group" value="Quality Assurance Analyst" checked type="radio">
                        <label for='g1o5'>Quality Assurance</label>
                        <input id='g1o6' name="group" value="Front End Developer" type="radio">
                        <label for='g1o6'>Front End Developer</label>
                    </fieldset>
                </div>

                <div class="submit">
                    <input type="submit" value="Submit" id="button-blue"/>
                    <div class="ease"></div>
                </div>
            </form>

        </div>
    </div>
