<?php
    $suggestedStudents = $this->getStudents();
?>
<div class="content">
    <div id="form-main">
        <div id="form-div">
            <form class="uk-form" id="form" action="http://apprentice.dev/incubate/schedule/student" method="post">

                <div class="uk-form-row">
                    Suggested students to invite:
                </div>
                <p>
                    Based on Lesson tags for Application Engineers, Front End Developers and Quality Assurance Analysts,
                    and if the student has yet to take the class.
                </p>
                <div class="uk-form-row">
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myStudents">
                        <?php
                            foreach($suggestedStudents as $student) {
                                echo '<li>' . $student . '</li>';
                            }
                        ?>
                    </ul>
                </div>
                <div class="uk-form-row">
                    <div class="submit">
                        <input type="submit" value="Next" id="button-blue"/>
                        <div class="ease"></div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

