<div class="content">
    <?php if(Core_Model_Session::get('admin_status')) : ?>
    <a href="http://apprentice.dev/incubate/schedule/lesson">Create new lesson</a><br>
    <?php endif;?>
    <iframe src="https://www.google.com/calendar/embed?mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=blueacorn.com_j2d2fnauptd0u7mgnrf0u5e0ss%40group.calendar.google.com&amp;color=%232952A3&amp;src=blueacorn.com_u7a896ti833paot5p2drm0a75g%40group.calendar.google.com&amp;color=%23B1365F&amp;src=blueacorn.com_u1vc38ipo9ofls7d02fbkj6uis%40group.calendar.google.com&amp;color=%2323164E&amp;ctz=America%2FNew_York" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div>
