<div class="content">
    <iframe src="https://www.google.com/calendar/embed?mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=blueacorn.com_j2d2fnauptd0u7mgnrf0u5e0ss%40group.calendar.google.com&amp;color=%232952A3&amp;src=blueacorn.com_u7a896ti833paot5p2drm0a75g%40group.calendar.google.com&amp;color=%23B1365F&amp;ctz=America%2FNew_York" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div>
