
<div class="content">
    <div class="uk-grid">
        <div class="uk-width-1-2">
        <div id="form-main">
            <div id="form-div">
                <form class="uk-form" id="form" action="http://apprentice.dev/incubate/schedule/datetime" method="post">
                    <div class="uk-grid">
                        <div class="uk-width-1-2">
                            Date:
                            <input type="" name="date" data-uk-datepicker="{format:'MM/DD/YYYY'}">
                        </div>
                        <div class="uk-width-1-2">
                            Time:
                            <div class="uk-autocomplete">
                                <input type="text" name="start_time" data-uk-timepicker="{format:'12h'}">
                            </div>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="uk-form-row">
                        <div class="submit">
                            <input type="submit" value="Next" id="button-blue"/>
                            <div class="ease"></div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
        <div id="calendar" class="uk-width-1-2">
            <iframe src="https://www.google.com/calendar/embed?mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=blueacorn.com_j2d2fnauptd0u7mgnrf0u5e0ss%40group.calendar.google.com&amp;color=%232952A3&amp;src=blueacorn.com_u7a896ti833paot5p2drm0a75g%40group.calendar.google.com&amp;color=%23B1365F&amp;src=blueacorn.com_u1vc38ipo9ofls7d02fbkj6uis%40group.calendar.google.com&amp;color=%2323164E&amp;ctz=America%2FNew_York" style=" border-width:0 " width="500" height="300" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>
</div>



