
<div class="content">
    <div id="form-main">
        <div id="form-div">
            <form class="uk-form" id="form" action="http://apprentice.dev/incubate/create/index/lesson" method="post">

                <div class="uk-form-row">
                    <input name="name" type="text" placeholder="Name" id="name" />
                </div>
                <div class="uk-form-row">
                    <textarea name="description" id="description" placeholder="Description"></textarea>
                </div>
                <div class="uk-form-row">
                    <label for=fader>Duration</label>

                    <input name="duration" type=range min=0 max=180 value=50 id=fader step=1 oninput="outputUpdate(value)">

                    <output for=fader id=duration>50 min.</output>
                    <script>
                        function outputUpdate(vol) {
                            document.querySelector('#duration').value = vol + ' min.';
                        }
                    </script>
                </div>
                <div class="uk-form-row">
                    Tags:
                </div>
                <div class="uk-form-row">
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myTags"></ul>
                </div>

                <div class="submit">
                    <input type="submit" value="Create" id="button-blue"/>
                    <div class="ease"></div>
                </div>
            </form>

        <iframe src="https://www.google.com/calendar/embed?showPrint=0&amp;mode=WEEK&amp;height=500&amp;wkst=1&amp;bgcolor=%23c0c0c0&amp;src=blueacorn.com_j2d2fnauptd0u7mgnrf0u5e0ss%40group.calendar.google.com&amp;color=%232952A3&amp;src=blueacorn.com_u7a896ti833paot5p2drm0a75g%40group.calendar.google.com&amp;color=%23B1365F&amp;src=blueacorn.com_u1vc38ipo9ofls7d02fbkj6uis%40group.calendar.google.com&amp;color=%2323164E&amp;ctz=America%2FNew_York" style=" border:solid 1px #777 " width="900" height="500" frameborder="0" scrolling="no"></iframe>
    </div>
</div>
