
<div class="content">
    <div id="form-main">
        <div id="form-div">
            <form class="uk-form" id="form" action="http://apprentice.dev/incubate/schedule/lesson" method="post">

                <div class="uk-form-row">
                    Lesson Name:
                </div>
                <p>You can submit one and only one lesson.</p>
                <div class="uk-form-row">
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myLessons"></ul>
                </div>
                <div class="uk-form-row">
                    <div class="submit">
                        <input type="submit" value="Next" id="button-blue"/>
                        <div class="ease"></div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

