<?php
$lessonName = $this->getName();
$description = $this->getDescription();
$tags = $this->getTags();
$startDate = $this->getDate();
$startTime = $this->getStart();
$endTime = $this->getEnd();
$suggestedStudents = $this->getStudents();
?>
<div class="content">
            <h2>Google Calendar Event Form:</h2>
    <div id="form-main">
        <div id="form-div">
            <form class="uk-form" id="form" action="http://apprentice.dev/incubate/schedule/event" method="post">
                <div class="uk-form-row">
                    <label>Lesson Name:</label>
                    <br>
                    <input readonly type="text" name="lesson_name" value="<?php if(isset($lessonName)){echo $lessonName;}?>">
                    <a href="http://apprentice.dev/incubate/schedule/lesson"> change.</a>
                </div>
                <div class="uk-form-row">
                    <label>Description and Tags:</label>
                    <textarea type="text" name="description"><?php if(isset($description)) { echo $description . ' ';}
                        if(isset($tags)) { foreach($tags as $tag) { echo "#" . $tag . ' ';}} ?>
                    </textarea>
                </div>

                <div class="uk-form-row">
                    <label>Lesson Date:</label>
                    <br>
                    <input type="text" name="date" value="<?php if(isset($startDate)) {echo $startDate;}?>">
                </div>
                <div class="uk-form-row">
                    <label>Start Time:</label>
                    <br>
                    <input type="text" name="start_time" value="<?php if(isset($startTime)) {echo $startTime;}?>">
                </div>
                <div class="uk-form-row">
                    <label>End Time:</label>
                    <br>
                    <input type="text" name="end_time" value="<?php if(isset($endTime)) {echo $endTime;}?>">
                </div>
                <div class="uk-form-row">
                    <label>Students:</label>
                    <ul class="tagit ui-widget ui-widget-content ui-corner-all" id="myStudents">
                        <?php
                        foreach($suggestedStudents as $student) {
                            echo '<li>' . $student . '</li>';
                        }
                        ?>
                    </ul>
                </div>
                <div class="uk-form-row">
                    <div class="submit">
                        <input type="submit" value="Submit" id="button-blue"/>
                        <div class="ease"></div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

