<?php

$tags = $this->getTag();
?>
<div class="content">

    <?php if(Core_Model_Session::get('admin_status')) : ?>
        <a class="uk-button uk-button-large uk-button-success" href="http://apprentice.dev/incubate/create/index/lesson">Create Lesson</a>

        <a class="uk-button uk-button-large uk-button-primary" href="http://apprentice.dev/incubate/create/index/tag">&nbsp;&nbsp;Create Tags&nbsp;&nbsp;</a>
    <?php endif; ?>

    <table class="uk-table uk-table-hover uk-table-striped">
        <h1>Tags</h1>
        <tbody>
        <?php
        if(isset($tags)) {
            foreach($tags as $tag) {

                echo '<tr>';
                echo '<td>' . $tag->name . '</td>';

                echo '<td><a class="uk-button uk-button-success" href="http://apprentice.dev/incubate/tag/edit/' . $tag->id .'">&nbsp;&nbsp;&nbsp;&nbsp;Edit&nbsp;&nbsp;&nbsp;&nbsp;</a></td>';

                echo '<td><a class="uk-button uk-button-danger" href="http://apprentice.dev/incubate/tag/delete/' . $tag->id .'">&nbsp;&nbsp;Delete&nbsp;&nbsp;</a></td>';

            }

            echo '</tr>';
        }
        ?>
        </tbody>
    </table>
</div>
