<?php
    $tags = $this->getTag();
?>



<div class="content">
    <?php foreach($tags as $tag) {?>
        <div id="box">
            <div class="box-top"><?php echo $tag->name; ?></div>
            <div class="box-panel"><?php var_dump( $tag); ?></div>
        </div>
    <?php }?>

    <div id="form-main">
        <div id="form-div">
            <form class="form" id="form1" action="http://apprentice.dev/incubate/create/tag" method="post">

                <p class="name">
                    <input name="name" type="text" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Name" id="name" />
                </p>

                <p class="tags">
                    <input name="tags" type="text" class="validate[required,custom[email]] feedback-input" id="tags" placeholder="Tags" />
                </p>

                <p class="text">
                    <textarea name="description" class="validate[required,length[6,300]] feedback-input" id="description" placeholder="Description"></textarea>
                </p>


                <div class="submit">
                    <input type="submit" value="Create" id="button-blue"/>
                    <div class="ease"></div>
                </div>
            </form>
        </div>
    </div>
</div>