<?php
    $userData = $this->getData('userData');
?>

<div class="content">
    <span id="clock"></span>
    <div data-countdown="2016/01/01"></div>
    <div data-countdown="2017/01/01"></div>
<table class="uk-table uk-table-hover uk-table-striped">
    <h1>Bators</h1>
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Email
        </th>
        <th>
            Title
        </th>
        <th>
            Group
        </th>
        <th>
            Role
        </th>
        <th>
            Tags
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($userData as $user) {
        echo '<tr>';
        echo '<td>' . $user->name . '</td>';
        echo '<td>' . $user->email . '</td>';
        echo '<td>' . 'n/a' . '</td>';
        echo '<td>' . $user->role . '</td>';
        echo '</tr>';
        }
    ?>
    </tbody>
</table>

    <?php foreach($userData as $user) {?>
    <div id="box">
        <div class="box-top"><?php echo $user->name; ?></div>
        <div class="box-panel"><?php var_dump( $user); ?></div>
    </div>
    <?php }?>
</div>