<?php
    $userData = $this->getData('userData');
    $userCompletedCourses = $this->getData('userCompletedCourses');
    $totalLessonCount = $this->getData('totalLessonCount');
?>

<div class="content">
<table class="uk-table uk-table-hover uk-table-striped">
    <h1>Bators</h1>
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Incubation Time
        </th>
        <th>
            Group
        </th>
        <th>
            Percentage of Courses Taken
        </th>
        <th>
            Admin Stuff
        </th>
    </tr>
    </thead>
    <tbody>

    <?php
		if(isset($userData)) {
			foreach($userData as $user) {

			$incubationTimer = date('Y-m-d', strtotime($user->joined . "+90 days"));
			if($totalLessonCount != 0) {
				$userProgress = round($userCompletedCourses[$user->name] / $totalLessonCount * 100);
			}
			else {
				$userProgress = 0;
			}
			echo '<tr>';
			echo '<td>' . $user->name . '</td>';
			echo '<td><div data-countdown="' . $incubationTimer . '"></div></td>';
			echo '<td>' . $user->groups . '</td>';
			echo '<td>';
			echo '<div class="uk-progress"><div class="uk-progress-bar" style="width:' . $userProgress .'%">' . $userProgress . '%</div></div>';
			echo '</td>';
			echo '<td><a class="uk-button  uk-button-danger" href="http://apprentice.dev/incubate/user/profile/' . $user->user_id . '">Edit</a></td>';
			echo '</tr>';
			}
		} else
		echo '<h2>There are no students to list</h2>';
    ?>
    </tbody>
</table
</div>