<div class="container">
    <div class="row centered-form">
            <div class="row">
                <form action="" method="post" role="form">
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input type="password" name="current_password" id="current_password" class="form-control input-sm" placeholder="Current Password">
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input type="password" name="new_password" id="new_password" class="form-control input-sm" placeholder="New Password">
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input type="password" name="new_password_confirmation" id="new_password_confirmation" class="form-control input-sm" placeholder="Confirm New Password">
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                    <input type="submit" value="Change" class="btn btn-info btn-block">
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>

