<div class="container">
    <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
            <form action="../update/index" method="post">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" value="<?php echo $this->getUser()->name; ?>">
                    <input type="submit" value="Update" class="btn btn-info btn-block">
                </div>
            </form>
        </div>
    </div>
</div>